### ISSUE TITLE
openPli

### ISSUE THREAD

**Issue by Dima73** [mx3L/subssupport#5]
mx3L
This plugin can be added to the feed openPli?

**Comment by mx3L** [comment]
Hi, sure

**Comment by Dima73** [comment]
Checked.
On Pli everything is OK.
Soon I will add Russian localization.

There is only a problem. Russian subtitles are always in the wrong encoding.

Another question.
What are the difference ssubssupport and ddamir.subtitle.player?

and
How to add a plugin to the feed IPT, as ipk or build?

**Comment by Dima73** [comment]
![1_0_19_379f_44c_13e_820000_0_0_0](https://cloud.githubusercontent.com/assets/1756274/10704292/92fa419c-79de-11e5-9b59-2a4b8e3ea56f.jpg)

**Comment by Dima73** [comment]
Russian subtitles 90% in the wrong encoding

**Comment by mx3L** [comment]
Did you select russian encoding group in subssupport settings?
Main Menu -> Plugins -> SubsSupport settings -> Encoding = Russia

subssupport vs damir -> subssupport is fully open source, there is separate plugin for downloading subtitles, for playing dvb subtitles, also it's possible to embed SubsSupport class in your mediaplayer as is done in TSMedia, mediaplayer2 for improved subtitles support.
As for damir, I used it really long time ago so I can't tell you differences

How to add a plugin to the feed IPT, as ipk or build?
ipk

**Comment by Dima73** [comment]
-Main Menu -> Plugins -> SubsSupport settings -> Encoding = Russia-
Thanks, helped.
