### ISSUE TITLE
not enough arguments for format string

### ISSUE THREAD

**Issue by cellentano** [mx3L/subssupport#62]
Vyhladavanie titulkov funguje, ale vacsina sa neda stiahnut - "not enough arguments for format string".  Problem je na Titulky.com aj Opensubtitles. 
[subssupport.log](https://github.com/mx3L/subssupport/files/4399334/subssupport.log)

**Comment by fairbird** [comment]
@athoik 
Now the issue is as cellentano mentioned

![1](https://user-images.githubusercontent.com/1761779/77855514-9a6f4400-71f9-11ea-9706-d362891d26ae.jpg)

**Comment by athoik** [comment]
Not an issue with quote..

```
from twisted.web.client import getPage
from twisted.internet import reactor
from urllib2 import quote

queryString = "DARK SKIES"
url = "http://www.opensubtitles.org/libs/suggest.php?format=json2&SubLanguageID=null&MovieName=" + quote(queryString)

def print_and_stop(output):
    print output
    if reactor.running:
       reactor.stop()

if __name__ == '__main__':
    print 'fetching', url
    d = getPage(url)
    d.addCallback(print_and_stop)
    reactor.run()
```

```
fetching http://www.opensubtitles.org/libs/suggest.php?format=json2&SubLanguageID=null&MovieName=DARK%20SKIES
{"result":[{"name":"Dark Skies","year":"2013","total":"140","id":148758},{"name":"Dark Skies","year":"1996","total":"100","id":45997}]}
```

**Comment by fairbird** [comment]
It is ok ... The problem not from plugin ..
from (Subtitles download path) should be in correct path ..
.
![1](https://user-images.githubusercontent.com/1761779/77857266-1b800880-7205-11ea-819f-0ce18423e1e8.jpg)
![2](https://user-images.githubusercontent.com/1761779/77857268-1cb13580-7205-11ea-8b4b-f7e43d21e700.jpg)
.
> root@dm920:~# ls /ba/ddsubt
The.lord.of.the.rings.the.fellowp.of.the.ring.2001.1080p.bluray.srt

So no problem in plugin works just fine ...
Thank you

**Comment by fairbird** [comment]
but need to update some Prefered site such as (Subscene)

**Comment by cellentano** [comment]
There is no problem to search for subtitles. But some of them can be downloaded and open, some of them gives error. My download folder is /tmp/ and it doesnt contain subtitles files.
![IMG_20200329_212200](https://user-images.githubusercontent.com/25830542/77858452-f8088e00-7203-11ea-850c-cf05fdf24c45.jpg)
![IMG_20200329_212213](https://user-images.githubusercontent.com/25830542/77858460-05257d00-7204-11ea-9273-4859532d006a.jpg)

**Comment by cellentano** [comment]
btw, I tried it on 3 different receivers with same result

**Comment by fairbird** [comment]
The best way use your save file on usb or hdd ..
Create new folder on usb or hdd and from plugin settings select and set the new path ...
Then try again ...
/tmp directory on some image some time have some problem ...

**Comment by cellentano** [comment]
Changed to hdd and also temporary folder and same result.

**Comment by fairbird** [comment]
remove it .. reboot device and install again ..
On my DM920 works just fine only two Preferred doesn't work (Subscene, subtitles GR).

**Comment by cellentano** [comment]
Did as first step. No success. Maybe it is related to titulky.com and OpenSubtitles.
